#!/usr/bin/env bash
# display the content of the file /etc/passwd: only the username, the user id and the home directory path for the user
FILENAME="/etc/passwd"
while IFS= read -r line
do
echo "$line"
done < $FILENAME
