#!/usr/bin/env bash
#display the visitor IP along with the HTTP status code from the Apache log file: in format IP HTTP_CODE, in a list, with the command awk
awk '{print $1,$9}' apache-access.log    

