#!/usr/bin/env bash
#display Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line with the while loop
i=0
while [ $i -lt 10 ]
do
((i++))
if [[ "$i" == '10' ]]; then
echo "Hi" 
fi
echo "Best School"
done
