#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes: display hours from 0 to 12, display minutes from 1 to 59 with the while loop
m=1
while [ $m -lt 59 ]
do
    echo :"$m"
    h=0
    while [ $h -le 12 ]
    do
	echo "$h"
	(( h++ ))
	done
    (( m++ ))
    done
