#!/usr/bin/env bash
#script that gives you information about the school file: if it exists, and if so, if it's empty or not, and if it's a regular file or not
if [ -f "school" ];
then    
    echo "school file exists"
elif [ -f "school" ];
    then
      echo "school file is empty"
elif [ -f "school" ];
    then
	echo "school file is not empty"
elif [ -f "school" ];
    then
	echo "school file is a regular file"
else
	echo "school file does not exist"
	fi
    
