#!/usr/bin/env bash
#display a list of currently running processes: all processes,for all users, including those which might not have a TTY, with a user-oriented format, and show process hierarchy
ps -aux
