#!/usr/bin/env bash
#script that: creates the file /var/run/myscript.pid containing its PID, displays To infinity and beyond indefinitely, displays I hate the kill command when receiving a SIGTERM signal, displays Y U no love me?! when receiving a SIGINT signal, deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
touch /var/run/myscript.pid < $$
trap echo "I hate the kill command" SIGTERM
trap echo "Y U no love me?!" SIGINT
while :
do
echo "To infinity and beyond"
done    
