#!/usr/bin/env bash
# manage my process
pid=/var/run/my_process.pid

start() {
    ./manage_my_process &
    echo "$!" > "$pid"
}

stop() {
    sudo kill -15 "$(cat $pid)" &&
	rm -f "$pid"
}

case "$1" in
start)
start
echo 'manage_my_process started'
;;
stop)
stop
echo 'manage_my_process stopped'
;;
restart)
stop
start
echo 'manage_my_process restarted'
;;
*)
echo 'Usage: manage_my_process {start|stop|restart}'
esac 

exit 0 

